export const SET_PLAY = 'SET_PLAY'
export const SET_PAUSE = 'SET_PAUSE'
export const SET_SEQUENCE = 'SET_SEQUENCE'
export const ADD_CHANNEL = 'ADD_CHANNEL'
export const SELECT_CHANNEL = 'SELECT_CHANNEL'
